"use client";

import React, { useState, useEffect, useRef } from "react";
import { Search, Loader2, Sparkles } from "lucide-react";
import { Card } from "@champflimz/ui";

interface SearchResult {
  id: number;
  title: string;
  posterUrl?: string;
  releaseYear?: number;
  rating: number;
  description: string;
}

export default function SmartSearch() {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<SearchResult[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [isOpen, setIsOpen] = useState(false);
  const searchRef = useRef<HTMLDivElement>(null);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (searchRef.current && !searchRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  // Debounced AI Search
  useEffect(() => {
    const timer = setTimeout(async () => {
      if (query.trim().length < 2) {
        setResults([]);
        setIsSearching(false);
        return;
      }

      setIsSearching(true);
      try {
        // In a real app, this hits our NestJS API: GET /api/v1/ai/search?q=${query}
        const res = await fetch(`http://localhost:5000/api/v1/ai/search?q=${encodeURIComponent(query)}`);
        if (res.ok) {
          const data = await res.json();
          setResults(data);
        } else {
          // Mock data for showcase purposes if backend is down
          setResults([
            { id: 1, title: "Mock AI Result 1", rating: 8.5, description: "Generated by Gemini" },
            { id: 2, title: "Mock AI Result 2", rating: 7.9, description: "Based on semantic intent" }
          ]);
        }
      } catch (e) {
        console.error("Search failed", e);
        // Fallback mock
        setResults([
          { id: 1, title: "Inception", rating: 8.8, description: "A thief who steals corporate secrets through the use of dream-sharing technology..." },
          { id: 2, title: "Interstellar", rating: 8.6, description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival." }
        ]);
      } finally {
        setIsSearching(false);
        setIsOpen(true);
      }
    }, 400); // 400ms debounce

    return () => clearTimeout(timer);
  }, [query]);

  return (
    <div className="relative w-full max-w-md z-50" ref={searchRef}>
      <div className="relative group">
        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          {isSearching ? (
            <Loader2 className="h-5 w-5 text-[var(--color-accent-500)] animate-spin" />
          ) : (
            <Search className="h-5 w-5 text-white/50 group-focus-within:text-[var(--color-accent-500)] transition-colors" />
          )}
        </div>
        <input
          type="text"
          className="w-full bg-[var(--color-surface-2)] border border-white/10 rounded-full py-2.5 pl-10 pr-10 text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-[var(--color-accent-500)] focus:bg-[var(--color-surface-1)] transition-all duration-[var(--duration-fast)]"
          placeholder="Semantic Search (e.g., 'a movie about dreams')"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onClick={() => query.trim().length > 1 && setIsOpen(true)}
        />
        <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
          <Sparkles className="h-4 w-4 text-[var(--color-accent-500)] opacity-70" />
        </div>
      </div>

      {isOpen && query.trim().length > 1 && (
        <Card className="absolute top-full mt-2 w-full max-h-[400px] overflow-y-auto glass-panel p-2 shadow-[var(--shadow-overlay)] animate-in fade-in slide-in-from-top-4 duration-200">
          {isSearching && results.length === 0 ? (
            <div className="p-4 text-center text-sm text-white/60 flex items-center justify-center gap-2">
              <Loader2 className="h-4 w-4 animate-spin" /> 
              Consulting AI...
            </div>
          ) : results.length > 0 ? (
            <div className="flex flex-col gap-1">
              <div className="px-3 py-2 text-xs font-semibold text-[var(--color-accent-500)] uppercase tracking-wider flex items-center gap-1.5">
                <Sparkles className="h-3 w-3" />
                Semantic Matches
              </div>
              {results.map((result) => (
                <button
                  key={result.id}
                  className="w-full text-left px-3 py-3 rounded-md hover:bg-[var(--color-surface-3)] transition-colors flex items-start gap-3 group"
                >
                  <div className="w-12 h-16 bg-[var(--color-surface-4)] rounded flex-shrink-0 overflow-hidden">
                    {result.posterUrl && <img src={result.posterUrl} alt={result.title} className="w-full h-full object-cover" />}
                  </div>
                  <div className="flex flex-col overflow-hidden">
                    <span className="font-medium text-white truncate group-hover:text-[var(--color-accent-500)] transition-colors">
                      {result.title}
                    </span>
                    <span className="text-xs text-white/50 mt-0.5 flex items-center gap-1.5">
                      {result.releaseYear && <span>{result.releaseYear}</span>}
                      {result.releaseYear && <span>•</span>}
                      <span className="text-[var(--color-warning)]">★ {result.rating.toFixed(1)}</span>
                    </span>
                    <span className="text-xs text-white/60 mt-1 line-clamp-1">
                      {result.description}
                    </span>
                  </div>
                </button>
              ))}
            </div>
          ) : (
            <div className="p-8 text-center flex flex-col items-center gap-3">
              <Search className="h-8 w-8 text-white/20" />
              <div>
                <p className="text-sm font-medium text-white">We couldn&apos;t find anything for &quot;{query}&quot;</p>
                <p className="text-xs text-white/50 mt-1">Try adjusting your semantics</p>
              </div>
            </div>
          )}
        </Card>
      )}
    </div>
  );
}
